name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker Setup QEMU
      # You may pin to the exact commit or the version.
      # uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      uses: docker/setup-qemu-action@v3.6.0

          

      

